apiVersion: v1
kind: Pod
metadata:
  labels:
    name: redis
  name: redis
spec:
  containers:
    - name: redis
      image: redis
      args:
        - "app-creds"
        - "/usr/local/etc/app-creds"
      ports:
        - containerPort: 6379
      volumeMounts:
        - mountPath: "/usr/local/etc/"
          name: "app-creds"
  volumes:
    - name: "app-creds"
      secret:
        secretName: "secret-creds
