apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  labels:
    volume: pv
spec:
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  nfs:
    server: 68.183.146.0
    path: /share
